version: '3.9'

services:
  dmz_client:
    image: alpine:latest
    container_name: dmz_client
    command: ["sleep", "infinity"]
    cap_add:
      - NET_ADMIN  # Aggiunge permessi per gestire iptables
      - NET_RAW    # Necessario per alcuni comandi di rete
    networks:
      - dmz_network
    volumes:
      - ./init_fw_dmz.sh:/usr/local/bin/init_fw_dmz.sh
    entrypoint: ["/bin/sh", "/usr/local/bin/init_fw_dmz.sh"]
    restart: always

  traefik:
    image: traefik:v2.5
    container_name: traefik_proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - dmz_network
    restart: always

  db-server:
    image: mysql:latest
    container_name: db-server
    networks:
      - mz_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always

  client:
    image: alpine:latest
    container_name: client
    command: ["sleep", "infinity"]
    cap_add:
      - NET_ADMIN  # Aggiunge permessi per gestire iptables
      - NET_RAW    # Necessario per alcuni comandi di rete
    networks:
      - mz_network
    volumes:
      - ./init_fw_mz.sh:/usr/local/bin/init_fw_mz.sh
    entrypoint: ["/bin/sh", "/usr/local/bin/init_fw_mz.sh"]
    restart: always
    
  firewall_dmz:
    image: ubuntu:latest
    container_name: firewall_dmz
    cap_add:
      - NET_ADMIN  # Aggiunge permessi per gestire iptables
      - NET_RAW    # Necessario per alcuni comandi di rete
    networks:
      dmz_network:
        ipv4_address: 172.22.0.3
    volumes:
      - ./ufw_dmz.sh:/usr/local/bin/ufw_dmz.sh
    entrypoint: ["/bin/bash", "/usr/local/bin/ufw_dmz.sh"]
    restart: always

  firewall_mz:
    image: ubuntu:latest
    container_name: firewall_mz
    cap_add:
      - NET_ADMIN  # Aggiunge permessi per gestire iptables
      - NET_RAW    # Necessario per alcuni comandi di rete
    networks:
      mz_network:
        ipv4_address: 172.23.0.3
    volumes:
      - ./ufw_mz.sh:/usr/local/bin/ufw_mz.sh
    entrypoint: ["/bin/bash", "/usr/local/bin/ufw_mz.sh"]
    restart: always

networks:
  dmz_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
  mz_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1