entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  docker: {}
api:
  insecure: true

services:
  my-service:
    loadBalancer:
      servers:
        - url: "http://127.0.0.1"
